require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PopularVideosController do

  # This should return the minimal set of attributes required to create a valid
  # PopularVideo. As you add validations to PopularVideo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "url" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PopularVideosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all popular_videos as @popular_videos" do
      popular_video = PopularVideo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:popular_videos).should eq([popular_video])
    end
  end

  describe "GET show" do
    it "assigns the requested popular_video as @popular_video" do
      popular_video = PopularVideo.create! valid_attributes
      get :show, {:id => popular_video.to_param}, valid_session
      assigns(:popular_video).should eq(popular_video)
    end
  end

  describe "GET new" do
    it "assigns a new popular_video as @popular_video" do
      get :new, {}, valid_session
      assigns(:popular_video).should be_a_new(PopularVideo)
    end
  end

  describe "GET edit" do
    it "assigns the requested popular_video as @popular_video" do
      popular_video = PopularVideo.create! valid_attributes
      get :edit, {:id => popular_video.to_param}, valid_session
      assigns(:popular_video).should eq(popular_video)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PopularVideo" do
        expect {
          post :create, {:popular_video => valid_attributes}, valid_session
        }.to change(PopularVideo, :count).by(1)
      end

      it "assigns a newly created popular_video as @popular_video" do
        post :create, {:popular_video => valid_attributes}, valid_session
        assigns(:popular_video).should be_a(PopularVideo)
        assigns(:popular_video).should be_persisted
      end

      it "redirects to the created popular_video" do
        post :create, {:popular_video => valid_attributes}, valid_session
        response.should redirect_to(PopularVideo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved popular_video as @popular_video" do
        # Trigger the behavior that occurs when invalid params are submitted
        PopularVideo.any_instance.stub(:save).and_return(false)
        post :create, {:popular_video => { "url" => "invalid value" }}, valid_session
        assigns(:popular_video).should be_a_new(PopularVideo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PopularVideo.any_instance.stub(:save).and_return(false)
        post :create, {:popular_video => { "url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested popular_video" do
        popular_video = PopularVideo.create! valid_attributes
        # Assuming there are no other popular_videos in the database, this
        # specifies that the PopularVideo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PopularVideo.any_instance.should_receive(:update).with({ "url" => "MyString" })
        put :update, {:id => popular_video.to_param, :popular_video => { "url" => "MyString" }}, valid_session
      end

      it "assigns the requested popular_video as @popular_video" do
        popular_video = PopularVideo.create! valid_attributes
        put :update, {:id => popular_video.to_param, :popular_video => valid_attributes}, valid_session
        assigns(:popular_video).should eq(popular_video)
      end

      it "redirects to the popular_video" do
        popular_video = PopularVideo.create! valid_attributes
        put :update, {:id => popular_video.to_param, :popular_video => valid_attributes}, valid_session
        response.should redirect_to(popular_video)
      end
    end

    describe "with invalid params" do
      it "assigns the popular_video as @popular_video" do
        popular_video = PopularVideo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PopularVideo.any_instance.stub(:save).and_return(false)
        put :update, {:id => popular_video.to_param, :popular_video => { "url" => "invalid value" }}, valid_session
        assigns(:popular_video).should eq(popular_video)
      end

      it "re-renders the 'edit' template" do
        popular_video = PopularVideo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PopularVideo.any_instance.stub(:save).and_return(false)
        put :update, {:id => popular_video.to_param, :popular_video => { "url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested popular_video" do
      popular_video = PopularVideo.create! valid_attributes
      expect {
        delete :destroy, {:id => popular_video.to_param}, valid_session
      }.to change(PopularVideo, :count).by(-1)
    end

    it "redirects to the popular_videos list" do
      popular_video = PopularVideo.create! valid_attributes
      delete :destroy, {:id => popular_video.to_param}, valid_session
      response.should redirect_to(popular_videos_url)
    end
  end

end
