require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TalentVideosController do

  # This should return the minimal set of attributes required to create a valid
  # TalentVideo. As you add validations to TalentVideo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "url" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TalentVideosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all talent_videos as @talent_videos" do
      talent_video = TalentVideo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:talent_videos).should eq([talent_video])
    end
  end

  describe "GET show" do
    it "assigns the requested talent_video as @talent_video" do
      talent_video = TalentVideo.create! valid_attributes
      get :show, {:id => talent_video.to_param}, valid_session
      assigns(:talent_video).should eq(talent_video)
    end
  end

  describe "GET new" do
    it "assigns a new talent_video as @talent_video" do
      get :new, {}, valid_session
      assigns(:talent_video).should be_a_new(TalentVideo)
    end
  end

  describe "GET edit" do
    it "assigns the requested talent_video as @talent_video" do
      talent_video = TalentVideo.create! valid_attributes
      get :edit, {:id => talent_video.to_param}, valid_session
      assigns(:talent_video).should eq(talent_video)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TalentVideo" do
        expect {
          post :create, {:talent_video => valid_attributes}, valid_session
        }.to change(TalentVideo, :count).by(1)
      end

      it "assigns a newly created talent_video as @talent_video" do
        post :create, {:talent_video => valid_attributes}, valid_session
        assigns(:talent_video).should be_a(TalentVideo)
        assigns(:talent_video).should be_persisted
      end

      it "redirects to the created talent_video" do
        post :create, {:talent_video => valid_attributes}, valid_session
        response.should redirect_to(TalentVideo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved talent_video as @talent_video" do
        # Trigger the behavior that occurs when invalid params are submitted
        TalentVideo.any_instance.stub(:save).and_return(false)
        post :create, {:talent_video => { "url" => "invalid value" }}, valid_session
        assigns(:talent_video).should be_a_new(TalentVideo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TalentVideo.any_instance.stub(:save).and_return(false)
        post :create, {:talent_video => { "url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested talent_video" do
        talent_video = TalentVideo.create! valid_attributes
        # Assuming there are no other talent_videos in the database, this
        # specifies that the TalentVideo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TalentVideo.any_instance.should_receive(:update).with({ "url" => "MyString" })
        put :update, {:id => talent_video.to_param, :talent_video => { "url" => "MyString" }}, valid_session
      end

      it "assigns the requested talent_video as @talent_video" do
        talent_video = TalentVideo.create! valid_attributes
        put :update, {:id => talent_video.to_param, :talent_video => valid_attributes}, valid_session
        assigns(:talent_video).should eq(talent_video)
      end

      it "redirects to the talent_video" do
        talent_video = TalentVideo.create! valid_attributes
        put :update, {:id => talent_video.to_param, :talent_video => valid_attributes}, valid_session
        response.should redirect_to(talent_video)
      end
    end

    describe "with invalid params" do
      it "assigns the talent_video as @talent_video" do
        talent_video = TalentVideo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TalentVideo.any_instance.stub(:save).and_return(false)
        put :update, {:id => talent_video.to_param, :talent_video => { "url" => "invalid value" }}, valid_session
        assigns(:talent_video).should eq(talent_video)
      end

      it "re-renders the 'edit' template" do
        talent_video = TalentVideo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TalentVideo.any_instance.stub(:save).and_return(false)
        put :update, {:id => talent_video.to_param, :talent_video => { "url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested talent_video" do
      talent_video = TalentVideo.create! valid_attributes
      expect {
        delete :destroy, {:id => talent_video.to_param}, valid_session
      }.to change(TalentVideo, :count).by(-1)
    end

    it "redirects to the talent_videos list" do
      talent_video = TalentVideo.create! valid_attributes
      delete :destroy, {:id => talent_video.to_param}, valid_session
      response.should redirect_to(talent_videos_url)
    end
  end

end
