require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WebseriesController do

  # This should return the minimal set of attributes required to create a valid
  # Webseries. As you add validations to Webseries, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "url" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WebseriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all webseries as @webseries" do
      webseries = Webseries.create! valid_attributes
      get :index, {}, valid_session
      assigns(:webseries).should eq([webseries])
    end
  end

  describe "GET show" do
    it "assigns the requested webseries as @webseries" do
      webseries = Webseries.create! valid_attributes
      get :show, {:id => webseries.to_param}, valid_session
      assigns(:webseries).should eq(webseries)
    end
  end

  describe "GET new" do
    it "assigns a new webseries as @webseries" do
      get :new, {}, valid_session
      assigns(:webseries).should be_a_new(Webseries)
    end
  end

  describe "GET edit" do
    it "assigns the requested webseries as @webseries" do
      webseries = Webseries.create! valid_attributes
      get :edit, {:id => webseries.to_param}, valid_session
      assigns(:webseries).should eq(webseries)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Webseries" do
        expect {
          post :create, {:webseries => valid_attributes}, valid_session
        }.to change(Webseries, :count).by(1)
      end

      it "assigns a newly created webseries as @webseries" do
        post :create, {:webseries => valid_attributes}, valid_session
        assigns(:webseries).should be_a(Webseries)
        assigns(:webseries).should be_persisted
      end

      it "redirects to the created webseries" do
        post :create, {:webseries => valid_attributes}, valid_session
        response.should redirect_to(Webseries.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved webseries as @webseries" do
        # Trigger the behavior that occurs when invalid params are submitted
        Webseries.any_instance.stub(:save).and_return(false)
        post :create, {:webseries => { "url" => "invalid value" }}, valid_session
        assigns(:webseries).should be_a_new(Webseries)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Webseries.any_instance.stub(:save).and_return(false)
        post :create, {:webseries => { "url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested webseries" do
        webseries = Webseries.create! valid_attributes
        # Assuming there are no other webseries in the database, this
        # specifies that the Webseries created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Webseries.any_instance.should_receive(:update).with({ "url" => "MyString" })
        put :update, {:id => webseries.to_param, :webseries => { "url" => "MyString" }}, valid_session
      end

      it "assigns the requested webseries as @webseries" do
        webseries = Webseries.create! valid_attributes
        put :update, {:id => webseries.to_param, :webseries => valid_attributes}, valid_session
        assigns(:webseries).should eq(webseries)
      end

      it "redirects to the webseries" do
        webseries = Webseries.create! valid_attributes
        put :update, {:id => webseries.to_param, :webseries => valid_attributes}, valid_session
        response.should redirect_to(webseries)
      end
    end

    describe "with invalid params" do
      it "assigns the webseries as @webseries" do
        webseries = Webseries.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Webseries.any_instance.stub(:save).and_return(false)
        put :update, {:id => webseries.to_param, :webseries => { "url" => "invalid value" }}, valid_session
        assigns(:webseries).should eq(webseries)
      end

      it "re-renders the 'edit' template" do
        webseries = Webseries.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Webseries.any_instance.stub(:save).and_return(false)
        put :update, {:id => webseries.to_param, :webseries => { "url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested webseries" do
      webseries = Webseries.create! valid_attributes
      expect {
        delete :destroy, {:id => webseries.to_param}, valid_session
      }.to change(Webseries, :count).by(-1)
    end

    it "redirects to the webseries list" do
      webseries = Webseries.create! valid_attributes
      delete :destroy, {:id => webseries.to_param}, valid_session
      response.should redirect_to(webseries_index_url)
    end
  end

end
